version: '3.8'
name: docrecall-stack
services:

  # https://docs.paradedb.com/documentation/getting-started/quickstart
  paradedb:
    image: paradedb/paradedb:0.15.1-pg17
    ports:
      - "5432:5432"
    ulimits:
      nofile: 262144
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=docrecall
    volumes:
      - paradedb_data:/var/lib/postgresql/data/

volumes:
  paradedb_data:
